 
<link href="https://fonts.loli.net/css?family=Noto+Serif+SC:400,500,700&display=swap&subset=chinese-simplified"  rel="stylesheet">

<link href="https://fonts.loli.net/css?family=Parisienne"  rel="stylesheet">

<link href="https://fonts.loli.net/css?family=Pinyon+Script"  rel="stylesheet">
 
<link href="https://fonts.loli.net/css?family=EB+Garamond:400,500,700"   rel="stylesheet">
<link href="https://fonts.loli.net/css?family=Source+Code+Pro:400,700"  rel="stylesheet">
